global:
  serviceaccount:
    name: "toptal"

  imageCredentials:
    repositoryUriPrefix: "docker.io"

api:
  replicaCount: 5
  image:
    name: "koppula18/toptal_api"
    tag: "v1"
    pullPolicy: "Always"

  service:
    type: ClusterIP
    name: "toptal-api"
    protocol: "TCP"
    targetPort: "8018"
    port: "8018"


web:
  replicaCount: 5
  image:
    name: "koppula18/toptal_web"
    tag: "v1"
    pullPolicy: "Always"

  service:
    type: "LoadBalancer"
    name: "toptal-web"
    protocol: "TCP"
    targetPort: "web"
    port: "80"

db:
  replicaCount: 1
  dbname: "postgres"
  dbuser: "postgres"
  dbport: "5432"
  image:
    name: "postgres"
    tag: "latest"
    pullPolicy: "Always"
  persistence:
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClass:
  service:
    type: ClusterIP