---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-svc
  namespace: {{ .Release.Namespace }}

spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - name: {{ .Values.api.service.name }}
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: {{ .Values.api.service.protocol }}

