---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-config
  namespace: {{ .Release.Namespace }}
data:
  PGDATA: "/var/lib/postgresql/data/db-files"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-initdb-config
  namespace: {{ .Release.Namespace }}
data:
  PGDATA: "/var/lib/postgresql/data/db-files"
