---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.db.service.type }}
  selector:
    app: {{ .Release.Name }}-database
  ports:
    - port: 5432

