---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-svc
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: {{ .Values.web.service.type }}
  selector:
    app: {{ .Release.Name }}-web
  ports:
    - name: {{ .Values.web.service.name }}
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
      protocol: {{ .Values.web.service.protocol }}

